"""empty message

Revision ID: 024dd0478181
Revises: c843aae6627b
Create Date: 2023-12-06 05:56:28.469546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '024dd0478181'
down_revision = 'c843aae6627b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procedimientos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idUser', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['idUser'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procedimientos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('idUser')

    # ### end Alembic commands ###