"""empty message

Revision ID: 04dfaa6da57d
Revises: a2ae51f76da4
Create Date: 2023-12-05 23:01:00.087752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04dfaa6da57d'
down_revision = 'a2ae51f76da4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procedimientos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archive', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procedimientos', schema=None) as batch_op:
        batch_op.drop_column('archive')

    # ### end Alembic commands ###