"""empty message

Revision ID: 1fc4cdcba732
Revises: faf2f83bc579
Create Date: 2023-12-05 20:46:00.517370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fc4cdcba732'
down_revision = 'faf2f83bc579'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procedimientos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.alter_column('video',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procedimientos', schema=None) as batch_op:
        batch_op.alter_column('video',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.drop_column('is_active')
        batch_op.drop_column('link')

    # ### end Alembic commands ###