"""empty message

Revision ID: 7bdd4c1bc3ae
Revises: b01a3af9c107
Create Date: 2023-12-03 23:24:38.841007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bdd4c1bc3ae'
down_revision = 'b01a3af9c107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('degree', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('url_img', sa.String(length=250), nullable=False),
    sa.Column('idu_img', sa.String(length=250), nullable=False),
    sa.Column('num_contact', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('rol',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=13),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('rol',
               existing_type=sa.String(length=13),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    op.drop_table('usuario')
    # ### end Alembic commands ###