"""empty message

Revision ID: a2ae51f76da4
Revises: 1fc4cdcba732
Create Date: 2023-12-05 21:06:19.802757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2ae51f76da4'
down_revision = '1fc4cdcba732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procedimientos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.Text(), nullable=True))
        batch_op.drop_column('articulos')
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procedimientos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('articulos', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_column('photo')

    # ### end Alembic commands ###