"""empty message

Revision ID: b01a3af9c107
Revises: d05417b42b34
Create Date: 2023-11-25 03:31:04.777952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b01a3af9c107'
down_revision = 'd05417b42b34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('adress', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('country', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('department', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('photo', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('rol', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('professional_grade', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('workplace', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint(None, ['phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('workplace')
        batch_op.drop_column('professional_grade')
        batch_op.drop_column('rol')
        batch_op.drop_column('photo')
        batch_op.drop_column('department')
        batch_op.drop_column('country')
        batch_op.drop_column('adress')
        batch_op.drop_column('phone')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
