"""empty message

Revision ID: c843aae6627b
Revises: 04dfaa6da57d
Create Date: 2023-12-06 04:55:17.013105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c843aae6627b'
down_revision = '04dfaa6da57d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procedimientos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('subCategory', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procedimientos', schema=None) as batch_op:
        batch_op.drop_column('subCategory')
        batch_op.drop_column('category')

    # ### end Alembic commands ###