"""empty message

Revision ID: d05417b42b34
Revises: 5d0945e8be17
Create Date: 2023-11-11 17:09:47.517764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd05417b42b34'
down_revision = '5d0945e8be17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procedimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('articulos', sa.String(length=80), nullable=False),
    sa.Column('video', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('procedimientos')
    # ### end Alembic commands ###
